#!/bin/bash

source ~/.bashrc && conda activate donni

IN_DIR="input_fs"
OUT_DIR="inference"

model_file="/xdisk/rgutenk/lnt/software/donni/donni/custom_models.py"
model="out_of_africa"

# six nu, four m, three T, one misid
ubounds="1.1e2 1.1e2 1.1e2 1.1e2 1.1e2 1.1e2 11 11 11 11 2.1 2.1 2.1 1" 
lbounds="1e-3 1e-3 1e-3 1e-3 1e-3 1e-3 0 0 0 0 1e-3 1e-3 1e-3 1e-5"
grids="40 50 60"

i=$1 # for job array, the fs that we are on
printf -v j "%03d" $i # change $i to $j for index 3

date
echo "running fs ${i}"
dadi-cli InferDM --fs ${IN_DIR}/fs_${j} --model ${model} --model-file ${model_file} \
        --grids ${grids} --lbounds ${lbounds} --ubounds ${ubounds} \
        --output-prefix ${OUT_DIR}/fs_${j} --optimizations 100000 --cpus 50 \
        --check-convergence --delta-ll .0005 \
        --bestfit-p0-file ${OUT_DIR}/fs_${j}.InferDM.bestfits
date